const trocadilhos = [{pergunta:"Qual o nome do filme que fala sobre um cara que volta no tempo para terminar seu namoro?", resposta:"Ex-terminador do futuro"},
{pergunta:"Qual o nome da cidade que te oferece maconha?", resposta:"Quebéc"},
{pergunta:"Qual o achocolatado que os carecas mais bebem?", resposta:"Nescalvo"},
{pergunta:"Qual a dupla sertaneja que um de seus integrantes é muito viciado numa droga?", resposta:"Chitaozinho e Sóloló"},
{pergunta:"O que os animais disseram quando viram o tamanho da arca de Noé?", resposta:"No é possível"},
{pergunta:"o que o bebê dança quando está na barriga da mãe?", resposta:"Dança do ventre"},
{pergunta:"porque é bom beber o suco bem devagarinho?", resposta:"Porque ele fica suculento"},
{pergunta:"Qual o teorema preferido do Carlos Alberto de Nóbrega", resposta:"Teorema de La Place é nossa"},
{pergunta:"Qual o cantor brasileiro que o Trump não quer nos EUA?", resposta:"Latino"},
{pergunta:"Quem é o tarado que transa com carros?", resposta:"O maníaco do Parking"},
{pergunta:"Qual cidade incentiva o uso do tato?", resposta:"Tóquio"},
{pergunta:"Porque está chovendo na faculdade?", resposta:"Porque as nuvens estão se formando"},
{pergunta:"Quantos chocolates são necessários para voar?", resposta:"14 Bis"},
{pergunta:"Em qual filme o ex Papa é ladrão?", resposta:"E o Bento levou"},
{pergunta:"Qual remédio pode ser comprado na padaria?", resposta:"O buscoPão"},
{pergunta:"Qual sabor de sorvete é o mais consumido por bandidos?", resposta:"Cookies and crime"},
{pergunta:"Qual a princesa que quase não se preocupa com boletos pra pagar?", resposta:"Poca contas"},
{pergunta:"Qual o plano de saúde dos espíritas?", resposta:"Unimedium"},
{pergunta:"Qual o grupo de pagode da mulher que começou a ficar mais baixa?", resposta:"Ex alta samba"},
{pergunta:"O que o marido obediente pede quando chega no bar?", resposta:"Um Rum"},
{pergunta:"Qual sambista voava?", resposta:"Drone Ivone Lara"},
{pergunta:"Porque a jogadora de Baseball foi internada no hospício?", resposta:"Porque ela não batia bem"},
{pergunta:"Porque o Mickey não conseguiu entrar na Disneylândia?", resposta:"Porque ele não tinha um Pluto no bolso"},
{pergunta:"Qual inseto toma muito chá?", resposta:"MariBoldo"},
{pergunta:"Qual cantora avisa o Light Yagami quando o chá está pronto?", resposta:"CháKira"},
{pergunta:"Qual personagem do mortal Kombat sempre se despede do seu animal?", resposta:"TchauCão"},
{pergunta:"Qual jogo só funciona se fizer tudo o que ele quiser", resposta:"Campo mimado"},
{pergunta:"O Mario saiu e nunca mais voltou. Qual o nome do jogo?", resposta:"Mario Parte"},
{pergunta:"Um evangélico se apaionou por alguém da igreja. Qual o nome do jogo?", resposta:"Crente Crush"},
{pergunta:"Porque o Link não deixa o leite fora da geladeira?", resposta:"Porque ele aZelda"},
{pergunta:"Porque o médico do Luciano Huck receitou que ele jogasse League of legends?", resposta:"Porque Lolcura, Lolcura, Lolcura"},
{pergunta:"O que a mulher disse pra amiga que fazia dieta?", resposta:"Miga sua LouCarb"},
{pergunta:"Porque o Mario perdeu um processo para o Sonic", resposta:"Porque a justiça é Sega"},
{pergunta:"Qual a cerveja dos policiais?", resposta:"Skolta"},
{pergunta:"Qual a banda que incentiva o jovem a se tornar policial?", resposta:"Ser PM aos 22"},
{pergunta:"Qual a farinha usada pelos índios?", resposta:"Farinha de tribo"},
{pergunta:"Qual o doce mais agradeecido do mundo?", resposta:"Obrigadeiro"},
{pergunta:"Qual cantor está sempre na cena de um crime?", resposta:"Perito de Paula"},
{pergunta:"Qual mercado vende lagarto?", resposta:"Iguanabara"},
{pergunta:"Qual país que nunca paga imposto", resposta:"Sonegal"},
{pergunta:"Quando um extraterrestre cai, o que ele passa no machucado?", resposta:"Marteolate"},
{pergunta:"Quais são os frutos super decididos?", resposta:"Tomatitude"},
{pergunta:"Como uma galinha traficante vende drogas?", resposta:"Pó pó pó pó pó"},
{pergunta:"Qual a cidade peruana que odeia frangos?", resposta:"Mate o pinto"},
{pergunta:"Qual a espécie animal que precisa de você?", resposta:"AracNeedYou"},
{pergunta:"Porque o astronauta desistiu de fazer mingau com farinha de trigo?", resposta:"Porque a Via Láctea"},
{pergunta:"Qual o cachorro de rua no espaço?", resposta:"Vira láctea"},
{pergunta:"Qual o monarca que te protege dos mosquitos?", resposta:"O ReiPelente"},
{pergunta:"Qual o nome do cachorro que vai ler um livro?", resposta:"o Hot-vai-ler"},
{pergunta:"Qual pedra preciosa não gosta de relacionamentos oficiais?", resposta:"DiAmante"},
{pergunta:"Qual arroz muitos gostam de queimar?", resposta:"Arrosca"},
{pergunta:"O que eu falei pro Clodovil depois que ouvir Faroeste Caboclo?", resposta:"Faroeste Cabo Clô"},
{pergunta:"Qual a banda que os integrantes queriam ser Jesus?", resposta:"BeJesus"},
{pergunta:"Qual carro não quer ser dirigido pela Renata?", resposta:"ReNo"},
{pergunta:"Qual o doce preferido do advogado gaúcho?", resposta:"Doce de LeiChe"},
{pergunta:"Qual grupo musical onde todos estão resfriados?", resposta:"AtchimBalada"},
{pergunta:"Qual sobremesa o Trump não quer nos EUA?", resposta:"GeLatina"},
{pergunta:"Qual o carro que avisa quando vai chover?", resposta:"O Celta Preto"},
{pergunta:"Qual creme pra espinhas os astronautas usam?", resposta:"AcNasa"},
{pergunta:"Qual o brinquedo preferido das crianças russas nas festas juninas?", resposta:"Os Stalinhos"},
{pergunta:"Qual o maior pacifista de todos os tempos?", resposta:"Mahatma Grande"},
{pergunta:"Qual o filme em que um homem constrói uma ponte para conquistar um homossexual?", resposta:"Ponte para ter a bicha"},
{pergunta:"Qual o profissional que faz a contabilidade nos filmes pornô?", resposta:"Tesãoreiro"},
{pergunta:"Qual o ex jogador que não toma banho?", resposta:"O Edimundo"},
{pergunta:"Qual o peixe adolescente mais encontrado em bailes funk?", resposta:"O moleque piranha"},
{pergunta:"Qual matemático tinha uma régua feita de vento?", resposta:"Ar-Qui-Medes"},
{pergunta:"Qual ator de Hollywood tem a melhor mira do mundo?", resposta:"Wesley Sniper"},
{pergunta:"Porque não se pode falar o quinto mês do ano?", resposta:"Porque senão desMaio"},
{pergunta:"Qual personagem do folclore brasileiro é alucinado por roupas de couro?", resposta:"O CouroPira"},
{pergunta:"Qual a cantora que acabou de ganhar uma patente?", resposta:"A Major EsteAno"},
{pergunta:"Porque o guitarrista só faz a base quando está tomando sol?", resposta:"Pra deixar o protetor solar"},
{pergunta:"Qual cão que voa?", resposta:"O falCão"},
{pergunta:"Qual o anime preferido dos transformistas?", resposta:"Drag ball z"},
{pergunta:"Qual policial não gosta de gente com boca suja?", resposta:"Guardanapo"},
{pergunta:"Qual a história da princesa adolescente que não gosta de cobrir os pés?", resposta:"A Pequena sem meia"},
{pergunta:"Qual político me caguetou?", resposta:"José DisseEu"},
{pergunta:"Qual a cantora que obriga o irmão mais novo a dançar no carnaval?", resposta:"Sambe Júnior"},
{pergunta:"Qual programa de tv que dá de ombros pra platéia?", resposta:"Shoulder Xuxa"},
{pergunta:"Qual a serie das pessoas que não gostam de responder perguntas?", resposta:"Todo mundo odeia o quiz"},
{pergunta:"O que disseram pro Superman quado perceberam que ele tiha mudado muito?", resposta:"Kent viu Kent vê"},
{pergunta:"O ganso chama sua esposa pra aprender o alfabeto. Qual o nome do filme?", resposta:"V de vem gansa"},
{pergunta:"Que filme eu tenho que assistir sob ameaça de morte?", resposta:"Vingadores OuTeMato"},
{pergunta:"Qual parente sempre deixa um pouco de comida no prato?", resposta:"Sobrinha"},
{pergunta:"Qual a melhor coisa pra se desejar à um voyer no natal?", resposta:"Boas frestas!!"},
{pergunta:"Qual mágico tinha aids?", resposta:"Ma-H-Iver"},
{pergunta:"Porque o anão mesmo sem poder ter filhos é uma ótima companhia pra sua esposa doente?", resposta:"Porque o mini-estéril da saúde à diverte"},
{pergunta:"Qual cantora de MPB fede quando canta?", resposta:"Gal Bosta"},
{pergunta:"Qual super-herói abriu uma igreja?", resposta:"Homem de fé-rro"},
{pergunta:"Qual pastor nasceu em abril?", resposta:"R. R. SouÁries"},
{pergunta:"Qual desenho a gente assiste pra ir bem na prova?", resposta:"Vem 10"},
{pergunta:"Qual filme da pessoa que sempre canta enquanto se prepara pra fazer anal?", resposta:"Cantando na chuca"},
{pergunta:"Em que filme os protagonistas acabam sendo picados?", resposta:"Ninguém segura SBP"},
{pergunta:"Qual ator americano que sempre deixa todo mundo impressionado?", resposta:"Uau Paccino"},
{pergunta:"Porque Sherlock Holmes foi em uma corrida de Fórmula 1?", resposta:"Pra ir atrás de uma pista"},
{pergunta:"Qual ator nunca usa crédito?", resposta:"Danny Debito"},
{pergunta:"Qual filme conta a história de um cavalo de brinquedo?", resposta:"PocoTóy Story"},
{pergunta:"Qual a identidade secreta do herói que se tremia todo?", resposta:"Peter Parkinson"},
{pergunta:"Qual a identidade secreta do super herói evangélico?", resposta:"Clark Crente"},
{pergunta:"Você tenta aplicar um supositório mas ele cai, você pega e coloca de novo. Qual o nome do filme?", resposta:"De volta pro teu furo"},
{pergunta:"Quala serie em que pacientes de um hospício colocam dedos no ânus dos outros?", resposta:"Um maluco no dedaço"},
{pergunta:"Qual guerra foi comandada por pessoas que pintaram o cabelo de loiro claro?", resposta:"Guerra da FizPlatina"},
{pergunta:"Qual o caminho que só a mulher do filho pode seguir?", resposta:"Trilha sóNora"},
{pergunta:"O que o coveiro disse quando pediram pra ele gerenciar o cemitério?", resposta:"Isso não é da minha ossada"},
{pergunta:"O Detran mandou colocar um aviso em todas as maternidades. Qual foi o aviso?", resposta:"Se bebê não dirija"},
{pergunta:"Qual dinossauro que faz sequestros relâmpago?", resposta:"VelociRapto"},
{pergunta:"A funkeira ficou um mês com monges. O que ela disse quando saiu?", resposta:"Que retiro foi esse!!"},
{pergunta:"Qual banda de rocl mais faz sucesso na macumba?", resposta:"Led Zeplintra"},
{pergunta:"Qual atriz brasileira é fã do Sérgio malandro, mas não fala glú glú, nem ié ié?", resposta:"Renata Só-RÁ"},
{pergunta:"Qual doença transmitida pelo ratinho ladrão?", resposta:"Cleptospirose"},
{pergunta:"Qual a freira pacifista que também é matemática?", resposta:"Madre Teresa de Calcular"},
{pergunta:"O que o marciano foi fazer em São Paulo?", resposta:"Foi visitar o TioEtê"},
{pergunta:"Que personagem literário gosta de música nordestina?", resposta:"Dom Que-Xote"},
{pergunta:"Onde os X-Men andam de bicicleta?", resposta:"Na Ciclopvia"},
{pergunta:"O que a abelha falou pro urso que tava comendo o mel dela?", resposta:"Ei, isso é mel"},
{pergunta:"Qual farinha que as fadas usam?", resposta:"Farinha de condão"},
{pergunta:"Porque o mineiro com dor de cabeça sempre chega atrasado?", resposta:"Porque ele tomou um trem para-dor"},
{pergunta:"Qual a bebida do Carateca culto?", resposta:"Iá-cult"},
{pergunta:"Qual personagem é sempre o último a saber na Terra Média?", resposta:"ChiFrodo"},
{pergunta:"Qual atriz ia fazer uma aposta mas desistiu?", resposta:"Bet Faria"},
{pergunta:"O que o Buzz Lightyear disse pro amigo dele na ladeira?", resposta:"Role-Wood"},
{pergunta:"Qual apresentador já pode ir pra casa?", resposta:"Gugu Liberado"},
{pergunta:"Como se chama o animal mais mal caráter que existe?", resposta:"PiLontra"},
{pergunta:"Qual atriz nasceu mãe?", resposta:"Malu Mother"},
{pergunta:"O pirata estava aguardando seu barco mas não sabia o lugar certo para aguardar. O que ele perguntou?", resposta:"On-JackSperow?"},
{pergunta:"Qual ferramenta não está mais aqui?", resposta:"A foice"},
{pergunta:"Qual sanduíche preferido da Turma do Chaves?", resposta:"X-Pirito"},
{pergunta:"Qual o protetor dos fedidos e dos maus-cheirosos?", resposta:"Deusodorante"},
]
//{pergunta:"", resposta:""},