const trocadilhos = [{pergunta:"Qual o nome do filme que fala sobre um cara que volta no tempo para terminar seu namoro?", resposta:"Ex-terminador do futuro"},
{pergunta:"Qual o nome da cidade que te oferece maconha?", resposta:"Quebéc"},
{pergunta:"Qual o achocolatado que os carecas mais bebem?", resposta:"Nescalvo"},
{pergunta:"Qual a dupla sertaneja que um de seus integrantes é muito viciado numa droga?", resposta:"Chitaozinho e Sóloló"},
{pergunta:"O que os animais disseram quando viram o tamanho da arca de Noé?", resposta:"No é possível"},
{pergunta:"o que o bebê dança quando está na barriga da mãe?", resposta:"Dança do ventre"},
{pergunta:"porque é bom beber o suco bem devagarinho?", resposta:"Porque ele fica suculento"},
{pergunta:"Qual o teorema preferido do Carlos Alberto de Nóbrega", resposta:"Teorema de La Place é nossa"},
{pergunta:"Qual o cantor brasileiro que o Trump não quer nos EUA?", resposta:"Latino"},
{pergunta:"Quem é o tarado que transa com carros?", resposta:"O maníaco do Parking"},
{pergunta:"Qual cidade incentiva o uso do tato?", resposta:"Tóquio"},
{pergunta:"Porque está chovendo na faculdade?", resposta:"Porque as nuvens estão se formando"},
{pergunta:"Quantos chocolates são necessários para voar?", resposta:"14 Bis"},
{pergunta:"Em qual filme o ex Papa é ladrão?", resposta:"E o Bento levou"},
{pergunta:"Qual remédio pode ser comprado na padaria?", resposta:"O buscoPão"},
{pergunta:"Qual sabor de sorvete é o mais consumido por bandidos?", resposta:"Cookies and crime"},
{pergunta:"Qual a princesa que quase não se preocupa com boletos pra pagar?", resposta:"Poca contas"},
{pergunta:"Qual o plano de saúde dos espíritas?", resposta:"Unimedium"},
{pergunta:"Qual o grupo de pagode da mulher que começou a ficar mais baixa?", resposta:"Ex alta samba"},
{pergunta:"O que o marido obediente pede quando chega no bar?", resposta:"Um Rum"},
{pergunta:"Qual sambista voava?", resposta:"Drone Ivone Lara"},
{pergunta:"Porque a jogadora de Baseball foi internada no hospício?", resposta:"Porque ela não batia bem"},
{pergunta:"Porque o Mickey não conseguiu entrar na Disneylândia?", resposta:"Porque ele não tinha um Pluto no bolso"},
{pergunta:"Qual inseto toma muito chá?", resposta:"MariBoldo"},
{pergunta:"Qual cantora avisa o Light Yagami quando o chá está pronto?", resposta:"CháKira"},
{pergunta:"Qual personagem do mortal Kombat sempre se despede do seu animal?", resposta:"XiaoCão"},
{pergunta:"Qual jogo só funciona se fizer tudo o que ele quiser", resposta:"Campo mimado"},
{pergunta:"O Mario saiu e nunca mais voltou. Qual o nome do jogo?", resposta:"Mario Parte"},
{pergunta:"Um evangélico se apaionou por alguém da igreja. Qual o nome do jogo?", resposta:"Crente Crush"},
{pergunta:"Porque o Link não deixa o leite fora da geladeira?", resposta:"Porque ele aZelda"},
{pergunta:"Porque o médico do Luciano Huck receitou que ele jogasse League of legends?", resposta:"Porque Lolcura, Lolcura, Lolcura"},
{pergunta:"O que a mulher disse pra amiga que fazia dieta?", resposta:"Miga sua LouCarb"},
{pergunta:"Porque o Mario perdeu um processo para o Sonic", resposta:"Porque a justiça é Sega"},
{pergunta:"Qual a cerveja dos policiais?", resposta:"Skolta"},
{pergunta:"Qual a banda que incentiva o jovem a se tornar policial?", resposta:"Ser PM aos 22"},
{pergunta:"Qual a farinha usada pelos índios?", resposta:"Farinha de tribo"},
{pergunta:"Qual o doce mais agradeecido do mundo?", resposta:"Obrigadeiro"},
{pergunta:"Qual cantor está sempre na cena de um crime?", resposta:"Perito de Paula"},
{pergunta:"Qual mercado vende lagarto?", resposta:"Iguanabara"},
{pergunta:"Qual país que nunca paga imposto", resposta:"Sonegal"},
{pergunta:"Quando um extraterrestre cai, o que ele passa no machucado?", resposta:"Marteolate"},
{pergunta:"Quais são os frutos super decididos?", resposta:"Tomatitude"},
{pergunta:"Como uma galinha traficante vende drogas?", resposta:"Pó pó pó pó pó"},
{pergunta:"Qual a cidade peruana que odeia frangos?", resposta:"Mate o pinto"},
{pergunta:"Qual a espécie animal que precisa de você?", resposta:"AracNeedYou"},
{pergunta:"Porque o astronauta desistiu de fazer mingau com farinha de trigo?", resposta:"Porque a Via Láctea"},
{pergunta:"Qual o cachorro de rua no espaço?", resposta:"Vira láctea"},
{pergunta:"Qual o monarca que te protege dos mosquitos?", resposta:"O ReiPelente"},
{pergunta:"Qual o nome do cachorro que vai ler um livro?", resposta:"o Hot-vai-ler"},
{pergunta:"Qual pedra preciosa não gosta de relacionamentos oficiais?", resposta:"DiAmante"},
{pergunta:"Qual arroz muitos gostam de queimar?", resposta:"Arrosca"},
{pergunta:"O que eu falei pro Clodovil depois que ouvir Faroeste Caboclo?", resposta:"Faroeste Cabo Clô"},
{pergunta:"Qual a banda que os integrantes queriam ser Jesus?", resposta:"BeJesus"},
{pergunta:"Qual carro não quer ser dirigido pela Renata?", resposta:"ReNo"},
{pergunta:"Qual o doce preferido do advogado gaúcho?", resposta:"Doce de LeiChe"},
{pergunta:"Qual grupo musical onde todos estão resfriados?", resposta:"AtchimBalada"},
{pergunta:"Qual sobremesa o Trump não quer nos EUA?", resposta:"GeLatina"},
{pergunta:"Qual o carro que avisa quando vai chover?", resposta:"O Celta Preto"},
{pergunta:"Qual creme pra espinhas os astronautas usam?", resposta:"AcNasa"},
{pergunta:"Qual o brinquedo preferido das crianças russas nas festas juninas?", resposta:"Os Stalinhos"},
{pergunta:"Qual o maior pacifista de todos os tempos?", resposta:"Mahatma Grande"},
{pergunta:"Qual o filme em que um homem constrói uma ponte para conquistar um homossexual?", resposta:"Ponte para ter a bicha"},
{pergunta:"Qual o profissional que faz a contabilidade nos filmes pornô?", resposta:"Tesãoreiro"},
{pergunta:"Qual o ex jogador que não toma banho?", resposta:"O Edimundo"},
]
//{pergunta:"", resposta:""},